export type DocumentSolution = {
  number: string;
  slug: string;
  category: "Farm & Agribusiness" | "Funding & Investment" | "Corporate Documentation" | "Contracts & Tenders";
  title: string;
  summary: string;
  objective: string;
  idealFor: string[];
  focusAreas: string[];
  clientInputs: string[];
  deliverables: string[];
};

export const documentSolutions: DocumentSolution[] = [
  {
    number: "01",
    slug: "broiler-poultry-farm-business-plan",
    category: "Farm & Agribusiness",
    title: "Broiler Poultry Farm Business Plan",
    summary: "A production, marketing and financial plan for commercial broiler enterprises—from starter batches to scalable farms.",
    objective: "Translate the proposed flock size, production cycle, market route and available facilities into a credible operating and financing case.",
    idealFor: ["New poultry founders", "Existing farms seeking expansion", "Loan or grant applicants"],
    focusAreas: ["Flock-cycle planning", "Feed and mortality controls", "Housing and biosecurity", "Live-bird and dressed-bird routes", "Cash-flow sensitivity"],
    clientInputs: ["Proposed flock size", "Farm location and housing status", "Local chick, feed and selling prices", "Promoter experience", "Available and required capital"],
    deliverables: ["Custom business plan", "Three-to-five-year projection tables", "Implementation schedule", "Risk and biosecurity register", "Supporting-document checklist"],
  },
  {
    number: "02",
    slug: "layer-egg-production-business-plan",
    category: "Farm & Agribusiness",
    title: "Layer & Egg Production Business Plan",
    summary: "A structured plan for pullet acquisition, egg production, spent-layer sales and disciplined flock replacement.",
    objective: "Present the economics and operating controls of an egg enterprise across rearing, laying and replacement phases.",
    idealFor: ["Commercial egg producers", "Cooperatives", "Expansion-stage poultry farms"],
    focusAreas: ["Rearing-to-lay transition", "Egg grading and distribution", "Feed conversion", "Flock replacement", "Working-capital planning"],
    clientInputs: ["Target bird capacity", "Housing system", "Point-of-lay or day-old-chick route", "Local egg prices", "Distribution plan"],
    deliverables: ["Custom business plan", "Production-calendar model", "Financial projection tables", "Sales-channel plan", "Risk-control schedule"],
  },
  {
    number: "03",
    slug: "catfish-farming-business-plan",
    category: "Farm & Agribusiness",
    title: "Catfish Farming Business Plan",
    summary: "A complete grow-out and market plan covering pond capacity, stocking, feeding, water management and harvest strategy.",
    objective: "Convert pond infrastructure and target production volume into a practical fish-production and funding plan.",
    idealFor: ["New fish farms", "Existing pond operators", "Youth and cooperative projects"],
    focusAreas: ["Pond and water systems", "Stocking and survival", "Feed programme", "Harvest scheduling", "Fresh and smoked-fish markets"],
    clientInputs: ["Pond type and dimensions", "Water source", "Target stocking volume", "Fingerling and feed prices", "Target buyers"],
    deliverables: ["Custom business plan", "Production-cycle schedule", "Cost and revenue model", "Water and husbandry risk register", "Market-entry plan"],
  },
  {
    number: "04",
    slug: "cattle-fattening-business-plan",
    category: "Farm & Agribusiness",
    title: "Cattle Fattening Business Plan",
    summary: "A procurement, feeding, health and sales plan for short-cycle commercial cattle finishing.",
    objective: "Demonstrate how animal selection, feed sourcing, weight gain, health controls and market timing will produce sustainable margins.",
    idealFor: ["Livestock traders", "Commercial fattening yards", "Farmer groups and cooperatives"],
    focusAreas: ["Animal procurement", "Feed ration and sourcing", "Veterinary controls", "Market timing", "Loss and price sensitivity"],
    clientInputs: ["Target number of cattle", "Pen and water facilities", "Procurement market", "Feed-source quotations", "Planned sales periods"],
    deliverables: ["Custom business plan", "Batch operating model", "Cost and margin tables", "Animal-health protocol", "Procurement and sales schedule"],
  },
  {
    number: "05",
    slug: "goat-sheep-production-business-plan",
    category: "Farm & Agribusiness",
    title: "Goat & Sheep Production Business Plan",
    summary: "A breeding, fattening or combined small-ruminant enterprise plan tailored to land, feed and market conditions.",
    objective: "Frame a manageable herd-development model with credible husbandry, market and capital assumptions.",
    idealFor: ["Small-ruminant farms", "Women and youth groups", "Mixed-farm enterprises"],
    focusAreas: ["Breeding and replacement", "Housing and grazing", "Feed reserves", "Disease prevention", "Festive and year-round markets"],
    clientInputs: ["Breed and herd target", "Production system", "Land and housing", "Feed availability", "Buyer profile"],
    deliverables: ["Custom business plan", "Herd-growth schedule", "Financial projection tables", "Health and mortality controls", "Market calendar"],
  },
  {
    number: "06",
    slug: "rice-production-business-plan",
    category: "Farm & Agribusiness",
    title: "Rice Production Business Plan",
    summary: "A seasonal production and financing plan covering land preparation, inputs, field operations, harvest and market routes.",
    objective: "Present the technical calendar and unit economics of a rain-fed or irrigated rice enterprise.",
    idealFor: ["Individual growers", "Production clusters", "Outgrower and cooperative projects"],
    focusAreas: ["Land and water readiness", "Seed and input plan", "Mechanisation", "Harvest and post-harvest loss", "Off-taker strategy"],
    clientInputs: ["Hectares and location", "Water regime", "Expected input prices", "Equipment access", "Yield history or target"],
    deliverables: ["Custom business plan", "Seasonal activity calendar", "Per-hectare financial model", "Input and equipment schedule", "Market and risk plan"],
  },
  {
    number: "07",
    slug: "maize-production-business-plan",
    category: "Farm & Agribusiness",
    title: "Maize Production Business Plan",
    summary: "A field-production plan linking hectare targets, input timing, mechanisation, storage and buyer strategy.",
    objective: "Build a financeable maize-production case grounded in acreage, crop calendar, yield assumptions and market access.",
    idealFor: ["Commercial crop farmers", "Cooperatives", "Feed and grain supply projects"],
    focusAreas: ["Seed and fertility plan", "Weed and pest control", "Mechanised operations", "Drying and storage", "Feed-mill and market buyers"],
    clientInputs: ["Farm size and tenure", "Season and location", "Input quotations", "Historical yield", "Storage and sales plan"],
    deliverables: ["Custom business plan", "Crop calendar", "Per-hectare projection tables", "Input budget", "Post-harvest and market plan"],
  },
  {
    number: "08",
    slug: "irrigated-vegetable-farming-business-plan",
    category: "Farm & Agribusiness",
    title: "Irrigated Vegetable Farming Business Plan",
    summary: "A crop-cycle, irrigation, labour and market plan for tomato, pepper, onion and mixed-vegetable enterprises.",
    objective: "Structure staggered production and sales around water capacity, crop choice, seasonal prices and loss control.",
    idealFor: ["Dry-season farmers", "Market-garden operators", "Fresh-produce supply projects"],
    focusAreas: ["Crop selection and rotation", "Irrigation capacity", "Nursery and transplanting", "Perishability management", "Market timing"],
    clientInputs: ["Land and water details", "Selected crops", "Production season", "Input prices", "Buyer and transport plan"],
    deliverables: ["Custom business plan", "Staggered production calendar", "Crop-budget tables", "Irrigation and equipment plan", "Loss-control and sales strategy"],
  },
  {
    number: "09",
    slug: "greenhouse-hydroponics-business-plan",
    category: "Farm & Agribusiness",
    title: "Greenhouse & Hydroponics Business Plan",
    summary: "A controlled-environment agriculture plan integrating system choice, crop economics, utilities, skills and premium-market access.",
    objective: "Test technical and commercial feasibility before capital is committed to greenhouse or hydroponic infrastructure.",
    idealFor: ["Technology-led farms", "Urban agriculture founders", "Institutional demonstration projects"],
    focusAreas: ["System and crop selection", "Water and energy reliability", "Nutrient and climate controls", "Technical staffing", "Premium buyer validation"],
    clientInputs: ["Proposed system", "Site and utility data", "Target crops", "Supplier quotations", "Buyer research"],
    deliverables: ["Custom business plan", "Technical-system summary", "Capital and operating model", "Implementation roadmap", "Technical and market risk register"],
  },
  {
    number: "10",
    slug: "agrochemical-farm-input-distribution-plan",
    category: "Farm & Agribusiness",
    title: "Agrochemical & Farm-Input Distribution Plan",
    summary: "A compliance-conscious commercial plan for crop-protection products, seed, fertiliser, equipment and farmer advisory services.",
    objective: "Define a responsible sourcing, storage, sales and distribution system for an agricultural-input enterprise.",
    idealFor: ["Agro-dealers", "Regional distributors", "Farm-input retail networks"],
    focusAreas: ["Supplier due diligence", "Product portfolio", "Safe storage and handling", "Dealer and farmer channels", "Inventory discipline"],
    clientInputs: ["CAC and operating location", "Product categories", "Supplier information", "Warehouse or shop details", "Sales territory"],
    deliverables: ["Custom business plan", "Distribution-channel design", "Inventory and margin model", "Compliance-readiness checklist", "Sales and farmer-engagement plan"],
  },
  {
    number: "11",
    slug: "animal-feed-mill-business-plan",
    category: "Farm & Agribusiness",
    title: "Animal Feed Mill Business Plan",
    summary: "A raw-material, production, quality and market plan for poultry, fish or livestock feed operations.",
    objective: "Assess production capacity, formulation controls, raw-material security and customer demand before equipment investment.",
    idealFor: ["Feed producers", "Integrated farms", "Agricultural processing investors"],
    focusAreas: ["Product and species mix", "Raw-material sourcing", "Equipment capacity", "Quality assurance", "Dealer and farm sales"],
    clientInputs: ["Target feed products", "Machine quotations", "Raw-material prices", "Premises and utilities", "Target monthly capacity"],
    deliverables: ["Custom business plan", "Production-flow summary", "Capacity and costing model", "Quality-control plan", "Procurement and market strategy"],
  },
  {
    number: "12",
    slug: "grain-aggregation-storage-processing-plan",
    category: "Farm & Agribusiness",
    title: "Grain Aggregation, Storage & Processing Plan",
    summary: "A working-capital and operations plan for buying, conditioning, storing, processing and selling grain at commercial scale.",
    objective: "Show how procurement timing, quality control, storage discipline and buyer contracts protect capital and margins.",
    idealFor: ["Commodity aggregators", "Warehouse operators", "Processors and institutional suppliers"],
    focusAreas: ["Farmer and market sourcing", "Moisture and quality control", "Warehouse management", "Working-capital cycle", "Off-taker contracts"],
    clientInputs: ["Target commodities", "Planned volume", "Storage capacity", "Purchase and sales history", "Buyer requirements"],
    deliverables: ["Custom business plan", "Commodity-flow model", "Working-capital tables", "Storage-control plan", "Procurement and off-take strategy"],
  },
  {
    number: "13",
    slug: "general-sme-business-plan",
    category: "Corporate Documentation",
    title: "General SME Business Plan",
    summary: "A disciplined master plan for a new or existing small and medium-sized enterprise in services, trade, production or technology.",
    objective: "Turn the promoter's business idea and evidence into a coherent operating, marketing and financial roadmap.",
    idealFor: ["New ventures", "Growing owner-managed businesses", "Internal planning and financing discussions"],
    focusAreas: ["Business model", "Customer and competition", "Operations", "Management capacity", "Financial requirements"],
    clientInputs: ["Company records", "Products or services", "Market and pricing information", "Existing performance", "Capital request"],
    deliverables: ["Custom business plan", "Financial projection tables", "Implementation roadmap", "Risk register", "Document-readiness checklist"],
  },
  {
    number: "14",
    slug: "comprehensive-feasibility-study",
    category: "Funding & Investment",
    title: "Comprehensive Feasibility Study",
    summary: "An evidence-led assessment of technical, market, operational, financial and institutional viability before investment.",
    objective: "Help a promoter or decision-maker determine whether a proposed project should proceed, change scope or pause.",
    idealFor: ["Capital-intensive projects", "Boards and investors", "Expansion and location decisions"],
    focusAreas: ["Demand validation", "Technical alternatives", "Site and capacity", "Financial viability", "Sensitivity and decision gates"],
    clientInputs: ["Project concept", "Location and capacity", "Supplier quotations", "Market evidence", "Funding structure"],
    deliverables: ["Feasibility report", "Options assessment", "Financial viability tables", "Sensitivity analysis", "Go, revise or no-go recommendation framework"],
  },
  {
    number: "15",
    slug: "bank-loan-business-plan",
    category: "Funding & Investment",
    title: "Bank Loan Application Business Plan",
    summary: "A lender-facing business plan connecting the financing request to cash generation, repayment capacity, security and management controls.",
    objective: "Present a transparent financing case without overstating revenue, collateral, contracts or repayment ability.",
    idealFor: ["Businesses seeking term loans", "Asset-finance applicants", "Working-capital borrowers"],
    focusAreas: ["Facility purpose", "Borrower contribution", "Cash-flow and repayment", "Security documentation", "Downside sensitivity"],
    clientInputs: ["CAC and ownership records", "Bank statements or accounts", "Loan amount and terms", "Quotations", "Collateral and existing debt information"],
    deliverables: ["Lender-facing business plan", "Loan-use schedule", "Repayment and cash-flow tables", "Sensitivity notes", "Application-document checklist"],
  },
  {
    number: "16",
    slug: "grant-funding-proposal",
    category: "Funding & Investment",
    title: "Grant Funding Proposal",
    summary: "A funder-aligned proposal defining the problem, intervention, beneficiaries, activities, budget, outcomes and accountability system.",
    objective: "Match a genuine project to a specific call while making the logic, delivery capacity and measurable value easy to assess.",
    idealFor: ["Businesses and cooperatives", "NGOs and community organisations", "Innovation and livelihood projects"],
    focusAreas: ["Problem and evidence", "Theory of change", "Activities and work plan", "Budget justification", "Monitoring and sustainability"],
    clientInputs: ["Funding-call document", "Applicant records", "Project concept", "Beneficiary evidence", "Budget and implementation partners"],
    deliverables: ["Call-aligned proposal", "Logical framework", "Work plan", "Budget narrative", "Monitoring and reporting matrix"],
  },
  {
    number: "17",
    slug: "investor-partnership-proposal",
    category: "Funding & Investment",
    title: "Investor & Partnership Proposal",
    summary: "A decision-focused investment document presenting the opportunity, economics, governance, use of funds and partnership structure.",
    objective: "Enable serious commercial discussion while separating verified performance from forecasts and aspirations.",
    idealFor: ["Growth-stage businesses", "Joint-venture opportunities", "Strategic distribution and operating partnerships"],
    focusAreas: ["Opportunity and traction", "Commercial model", "Capital use", "Governance and roles", "Returns and exit discussion"],
    clientInputs: ["Company and promoter profile", "Historic performance", "Funding requirement", "Proposed terms", "Evidence of customers, assets or contracts"],
    deliverables: ["Investor proposal", "Use-of-funds schedule", "Commercial projection tables", "Partnership structure note", "Due-diligence checklist"],
  },
  {
    number: "18",
    slug: "company-profile-capability-statement",
    category: "Corporate Documentation",
    title: "Company Profile & Capability Statement",
    summary: "A concise, evidence-based presentation of an organisation's identity, services, leadership, resources and delivery capacity.",
    objective: "Give prospective clients and procurement teams a fast, credible understanding of what the organisation can actually deliver.",
    idealFor: ["Contractors and service providers", "Consultancies and technology companies", "Suppliers entering institutional markets"],
    focusAreas: ["Legal identity", "Service architecture", "Personnel and facilities", "Relevant experience", "Contact and verification details"],
    clientInputs: ["CAC documents", "Director and staff profiles", "Service list", "Verified project evidence", "Brand and contact assets"],
    deliverables: ["Branded company profile", "Two-page capability statement", "Corporate fact sheet", "Evidence register", "Tender-use PDF"],
  },
  {
    number: "19",
    slug: "expression-interest-prequalification-package",
    category: "Contracts & Tenders",
    title: "Expression of Interest & Prequalification Package",
    summary: "A submission-ready structure for organisations responding to genuine EOI and prequalification notices.",
    objective: "Map every published requirement to truthful evidence and present organisational capability in an evaluator-friendly order.",
    idealFor: ["Government contractors", "Institutional suppliers", "Consultants and service providers"],
    focusAreas: ["Requirement mapping", "Eligibility evidence", "Relevant experience", "Personnel and equipment", "Submission control"],
    clientInputs: ["Published notice", "CAC and tax records", "Licences where applicable", "Verified contracts and references", "Staff and equipment evidence"],
    deliverables: ["EOI response document", "Compliance matrix", "Evidence index", "Submission checklist", "Clarification and gap register"],
  },
  {
    number: "20",
    slug: "technical-financial-tender-proposal",
    category: "Contracts & Tenders",
    title: "Technical & Financial Tender Proposal",
    summary: "A requirement-led bid package integrating methodology, work plan, personnel, risk, pricing and submission controls.",
    objective: "Produce a clear, compliant and commercially disciplined response to a specific solicitation without fabricating qualifications or evidence.",
    idealFor: ["ICT and professional-service firms", "Works and supply contractors", "Training and consulting providers"],
    focusAreas: ["Tender compliance", "Technical methodology", "Work plan and staffing", "Quality and risk controls", "Pricing and assumptions"],
    clientInputs: ["Complete solicitation document", "Company compliance records", "Verified experience", "CVs and resource evidence", "Supplier quotations and pricing instructions"],
    deliverables: ["Technical proposal", "Financial proposal structure", "Compliance matrix", "Work plan and responsibility schedule", "Final submission-control checklist"],
  },
];

export const solutionCategories = [
  "Farm & Agribusiness",
  "Funding & Investment",
  "Corporate Documentation",
  "Contracts & Tenders",
] as const;

export function getDocumentSolution(slug: string) {
  return documentSolutions.find((solution) => solution.slug === slug);
}
