import type { Book } from "./content";

export const workingPublicationBooks: Book[] = [
  {
    title: "Hydroponic Mosque",
    slug: "hydroponic-mosque",
    subtitle: "A manuscript project in agriculture, learning, and community capability",
    category: "Agriculture / Education",
    description: "A preserved manuscript package with multiple source documents and HTML material. The public edition and cover authority are still being finalized.",
    audience: "Readers interested in agriculture education, community learning, practical skills, and institution-building.",
    learn: ["Publication package under editorial reconciliation", "Private manuscript evidence preserved", "Public release opens only after cover and edition approval"],
    contents: ["Private manuscript package", "Editorial packaging in progress", "Public table of contents pending final edition"],
    authorNote: "The manuscript package exists in the private archive. It is not presented as commercially released until the final edition and cover are approved.",
    price: "Coming soon",
    formats: ["Private manuscript", "HTML source package"],
    coverTone: "emerald",
    related: ["the-modern-farmer", "knowledge-is-seed", "the-climate-resilient-farmer"],
  },
  {
    title: "Web Development for World-Changers",
    slug: "web-development-for-world-changers",
    subtitle: "A web-development teaching and publishing package",
    category: "Technology / Education",
    description: "A substantial web-development package with master HTML, dossier material, and multiple content batches. Editorial review is deciding the final boundary between book and curriculum edition.",
    audience: "Students, beginner developers, educators, training centres, and practical technology learners.",
    learn: ["Web-development learning architecture", "Practical publishing-ready technical content", "Final book-versus-curriculum identity remains under review"],
    contents: ["Master HTML package", "Supporting dossier", "Multi-part teaching content"],
    authorNote: "The source package is strong, but the final public identity as a standalone book or curriculum product is still under editorial review.",
    price: "Coming soon",
    formats: ["Private master HTML", "Private dossier package"],
    coverTone: "navy",
    related: ["cheating-time", "a-multilingual-mind"],
  },
  {
    title: "Engineering the Journey",
    slug: "engineering-the-journey",
    subtitle: "A manuscript on formation, engineering, movement, and lived experience",
    category: "Engineering / Memoir",
    description: "An authored manuscript with a dedicated cover already preserved in the private archive. Final publication packaging remains in progress.",
    audience: "Students, engineers, travellers, educators, and readers interested in learning through technical and cross-cultural experience.",
    learn: ["A documented manuscript exists", "Dedicated cover evidence is preserved", "Final public packaging and metadata remain under review"],
    contents: ["Private authored manuscript", "Dedicated cover package", "Release metadata pending"],
    authorNote: "A manuscript and cover exist. The public edition remains forthcoming until the production package is fully reconciled.",
    price: "Coming soon",
    formats: ["Private DOCX manuscript", "Cover asset"],
    coverTone: "navy",
    related: ["the-global-seeker", "a-multilingual-mind", "kanuri-heart-chinese-tongue"],
  },
  {
    title: "The Global Seeker",
    slug: "the-global-seeker",
    subtitle: "A developing work on movement, study, and intellectual exploration",
    category: "Travel / Knowledge",
    description: "A Canon title currently evidenced by a two-book visual mockup while its standalone manuscript source is still being isolated from the archive.",
    audience: "Travellers, students, multilingual readers, and people interested in learning across cultures and places.",
    learn: ["Title and visual evidence preserved", "Standalone manuscript source still requires isolation", "No commercial release is asserted yet"],
    contents: ["Visual publication evidence", "Standalone source isolation pending"],
    authorNote: "This title remains in the Canon as a developing work. The standalone source must be isolated before release-ready status is granted.",
    price: "Coming soon",
    formats: ["Archive visual evidence"],
    coverTone: "gold",
    related: ["engineering-the-journey", "kanuri-heart-chinese-tongue", "a-multilingual-mind"],
  },
  {
    title: "Nurturing Seekers of Truth",
    slug: "nurturing-seekers-of-truth",
    subtitle: "A manuscript on learning, formation, and serious inquiry",
    category: "Education / Reflection",
    description: "An authored manuscript preserved in the private archive and awaiting final cover, metadata, and release packaging.",
    audience: "Students, teachers, mentors, parents, and readers interested in disciplined intellectual and moral formation.",
    learn: ["Private manuscript evidence exists", "Cover and final packaging remain open", "Public release remains forthcoming"],
    contents: ["Private authored manuscript", "Final public table of contents pending packaging"],
    authorNote: "The manuscript exists as an editable private source. It is not yet presented as release-ready until the cover and publication package are completed.",
    price: "Coming soon",
    formats: ["Private DOCX manuscript"],
    coverTone: "deep",
    related: ["knowledge-is-seed", "the-book-of-signs"],
  },
  {
    title: "Prophet's Eloquence",
    slug: "prophets-eloquence",
    subtitle: "A developing work in language, eloquence, and Islamic literary study",
    category: "Islamic Scholarship / Language",
    description: "A known Musa Allama Canon title whose standalone source still needs to be isolated from the wider archive before public-edition packaging can be completed.",
    audience: "Students of Arabic, rhetoric, Islamic scholarship, literature, and devotional intellectual traditions.",
    learn: ["Canon identity preserved", "Standalone source isolation remains open", "Release status is forthcoming rather than commercial"],
    contents: ["Archive source isolation pending", "Editorial structure pending confirmation"],
    authorNote: "The title is preserved in the publication registry, but the standalone source is not yet sufficiently isolated for a public master.",
    price: "Coming soon",
    formats: ["Archive source pending isolation"],
    coverTone: "gold",
    related: ["nurturing-seekers-of-truth", "the-book-of-signs"],
  },
  {
    title: "The Soul Who Will Never Disappoint",
    slug: "the-soul-who-will-never-disappoint",
    subtitle: "A developing reflective and spiritual work",
    category: "Reflection / Spirituality",
    description: "A Canon title retained from the private archive while the standalone manuscript source is being isolated and prepared for formal packaging.",
    audience: "Readers of reflective prose, spirituality, inner discipline, and literary contemplation.",
    learn: ["Canon identity preserved", "Standalone source still requires isolation", "No public sale or full-file delivery is enabled"],
    contents: ["Archive source isolation pending", "Final edition architecture pending"],
    authorNote: "The work remains forthcoming until its standalone source and final edition package are confirmed.",
    price: "Coming soon",
    formats: ["Archive source pending isolation"],
    coverTone: "burgundy",
    related: ["the-book-of-signs", "nurturing-seekers-of-truth"],
  },
  {
    title: "Bridge of Meaning",
    slug: "bridge-of-meaning",
    subtitle: "Language, translation, understanding, and the work between worlds",
    category: "Languages / Translation",
    description: "A publication project with dedicated cover evidence already preserved while the authoritative manuscript source is being isolated for final packaging.",
    audience: "Translators, language students, educators, cross-cultural operators, and readers interested in meaning across languages.",
    learn: ["Dedicated cover evidence exists", "Manuscript isolation is the remaining production task", "Release remains forthcoming until source authority is complete"],
    contents: ["Cover authority evidence", "Manuscript isolation in progress", "Final public contents pending"],
    authorNote: "The cover family is preserved. The publication remains in packaging review until the authoritative manuscript source is isolated.",
    price: "Coming soon",
    formats: ["Cover asset", "Private manuscript source under reconciliation"],
    coverTone: "navy",
    related: ["a-multilingual-mind", "kanuri-heart-chinese-tongue", "the-entrepreneurial-polyglot"],
  },
  {
    title: "Kanuri Heart, Chinese Tongue",
    slug: "kanuri-heart-chinese-tongue",
    subtitle: "Language, culture, identity, and movement across worlds",
    category: "Languages / Culture",
    description: "A publication family with preserved cover evidence under the title variants Kanuri Heart, Chinese Tongue and A Kanuri Heart. Final title authority is still being reconciled.",
    audience: "Multilingual readers, students of culture and identity, translators, travellers, and readers interested in cross-cultural formation.",
    learn: ["Multiple cover/title witnesses are preserved", "Final title authority remains under reconciliation", "No duplicate book is created from the title variants"],
    contents: ["Title-lineage reconciliation", "Private source packaging", "Public edition forthcoming"],
    authorNote: "The two title variants are treated as one publication family until the final canonical title is formally locked.",
    price: "Coming soon",
    formats: ["Private publication family", "Cover variants"],
    coverTone: "burgundy",
    related: ["a-multilingual-mind", "engineering-the-journey", "the-global-seeker"],
  },
];
