import type { Book } from "./content";

export const workingPublicationBooks: Book[] = [
  {
    title: "Hydroponic Mosque",
    slug: "hydroponic-mosque",
    subtitle: "Agriculture, learning, community capability, and sustainable spaces",
    category: "Agriculture / Education",
    description: "A forthcoming work exploring how practical agriculture, education, sustainability, and community institutions can reinforce one another.",
    audience: "Readers interested in agriculture education, community learning, practical skills, sustainability, and institution-building.",
    learn: [
      "How agricultural learning can be integrated into community spaces.",
      "How hydroponics and practical food production can support education and resilience.",
      "How small institutions can become centres of useful knowledge and local capability.",
    ],
    contents: ["Community learning and agriculture", "Hydroponics and practical sustainability", "Skills, stewardship, and local capability"],
    authorNote: "Forthcoming from Musa Allama.",
    price: "Coming soon",
    formats: ["Digital", "Print"],
    coverTone: "emerald",
    related: ["the-modern-farmer", "knowledge-is-seed", "the-climate-resilient-farmer"],
  },
  {
    title: "Web Development for World-Changers",
    slug: "web-development-for-world-changers",
    subtitle: "A practical path from web foundations to useful digital products",
    category: "Technology / Education",
    description: "A practical learning work for people who want to understand the web by building useful pages, interfaces, and digital experiences.",
    audience: "Students, beginner developers, educators, training centres, and practical technology learners.",
    learn: [
      "How websites are structured and delivered.",
      "How HTML, CSS, JavaScript, and modern web thinking fit together.",
      "How to turn technical learning into useful projects and digital products.",
    ],
    contents: ["Web foundations", "Building interfaces", "From practice to real projects"],
    authorNote: "Forthcoming from Musa Allama.",
    price: "Coming soon",
    formats: ["Digital", "Print"],
    coverTone: "navy",
    related: ["cheating-time", "a-multilingual-mind"],
  },
  {
    title: "Engineering the Journey",
    slug: "engineering-the-journey",
    subtitle: "Formation, engineering, movement, and lived experience",
    category: "Engineering / Memoir",
    description: "A reflective journey through engineering, study, travel, adaptation, and the experiences that shape a technical mind across different worlds.",
    audience: "Students, engineers, travellers, educators, and readers interested in technical growth and cross-cultural experience.",
    learn: [
      "How technical education changes the way a person sees problems and systems.",
      "How travel and cultural movement reshape learning and perspective.",
      "How experience, discipline, and engineering thinking can reinforce one another.",
    ],
    contents: ["Formation and study", "Engineering and problem-solving", "Movement, culture, and perspective"],
    authorNote: "Forthcoming from Musa Allama.",
    price: "Coming soon",
    formats: ["Digital", "Print"],
    coverTone: "navy",
    related: ["the-global-seeker", "a-multilingual-mind", "kanuri-heart-chinese-tongue"],
  },
  {
    title: "The Global Seeker",
    slug: "the-global-seeker",
    subtitle: "Movement, study, curiosity, and intellectual exploration",
    category: "Travel / Knowledge",
    description: "A forthcoming work about learning through movement: crossing places, languages, disciplines, and cultures in search of broader understanding.",
    audience: "Travellers, students, multilingual readers, and people interested in learning across cultures and places.",
    learn: [
      "How travel can become a serious form of education.",
      "How curiosity grows when languages, places, and disciplines intersect.",
      "How to carry lessons from one environment into another.",
    ],
    contents: ["The habit of seeking", "Learning across borders", "Travel, language, and perspective"],
    authorNote: "Forthcoming from Musa Allama.",
    price: "Coming soon",
    formats: ["Digital", "Print"],
    coverTone: "gold",
    related: ["engineering-the-journey", "kanuri-heart-chinese-tongue", "a-multilingual-mind"],
  },
  {
    title: "Nurturing Seekers of Truth",
    slug: "nurturing-seekers-of-truth",
    subtitle: "Learning, formation, mentorship, and serious inquiry",
    category: "Education / Reflection",
    description: "A forthcoming work on cultivating curiosity, discipline, mentorship, intellectual honesty, and the habits that sustain lifelong learning.",
    audience: "Students, teachers, mentors, parents, and readers interested in disciplined intellectual and moral formation.",
    learn: [
      "How curiosity can be protected and disciplined rather than merely encouraged.",
      "How mentorship shapes intellectual confidence and responsibility.",
      "How serious inquiry becomes a lifelong practice.",
    ],
    contents: ["Curiosity and formation", "Mentorship and discipline", "The lifelong seeker"],
    authorNote: "Forthcoming from Musa Allama.",
    price: "Coming soon",
    formats: ["Digital", "Print"],
    coverTone: "deep",
    related: ["knowledge-is-seed", "the-book-of-signs"],
  },
  {
    title: "Prophet's Eloquence",
    slug: "prophets-eloquence",
    subtitle: "Language, eloquence, rhetoric, and Islamic literary study",
    category: "Islamic Scholarship / Language",
    description: "A forthcoming study of eloquence, expression, rhetoric, and the power of language within Islamic literary and devotional traditions.",
    audience: "Students of Arabic, rhetoric, Islamic scholarship, literature, and devotional intellectual traditions.",
    learn: [
      "How eloquence works through clarity, structure, rhythm, and meaning.",
      "How Arabic rhetorical traditions approach powerful expression.",
      "How language can carry intellectual, ethical, and devotional force.",
    ],
    contents: ["Language and eloquence", "Rhetoric and meaning", "Expression in the Islamic literary tradition"],
    authorNote: "Forthcoming from Musa Allama.",
    price: "Coming soon",
    formats: ["Digital", "Print"],
    coverTone: "gold",
    related: ["nurturing-seekers-of-truth", "the-book-of-signs"],
  },
  {
    title: "The Soul Who Will Never Disappoint",
    slug: "the-soul-who-will-never-disappoint",
    subtitle: "A reflective work on the inner life, constancy, and spiritual resilience",
    category: "Reflection / Spirituality",
    description: "A forthcoming reflective work on inner discipline, hope, constancy, self-knowledge, and the quiet architecture of spiritual resilience.",
    audience: "Readers of reflective prose, spirituality, inner discipline, and literary contemplation.",
    learn: [
      "How inner steadiness is cultivated over time.",
      "How reflection can sharpen self-knowledge and spiritual discipline.",
      "How hope and constancy shape a resilient inner life.",
    ],
    contents: ["The inner life", "Constancy and reflection", "Hope, discipline, and resilience"],
    authorNote: "Forthcoming from Musa Allama.",
    price: "Coming soon",
    formats: ["Digital", "Print"],
    coverTone: "burgundy",
    related: ["the-book-of-signs", "nurturing-seekers-of-truth"],
  },
  {
    title: "Bridge of Meaning",
    slug: "bridge-of-meaning",
    subtitle: "Language, translation, understanding, and the work between worlds",
    category: "Languages / Translation",
    description: "A forthcoming exploration of translation as more than word replacement: a disciplined act of carrying meaning, intention, tone, and culture between people.",
    audience: "Translators, language students, educators, cross-cultural operators, and readers interested in meaning across languages.",
    learn: [
      "Why good translation begins with meaning rather than isolated words.",
      "How culture, tone, and context affect understanding.",
      "How translators become bridges between different intellectual and social worlds.",
    ],
    contents: ["Meaning before words", "Culture and context", "Translation as a bridge"],
    authorNote: "Forthcoming from Musa Allama.",
    price: "Coming soon",
    formats: ["Digital", "Print"],
    coverTone: "navy",
    related: ["a-multilingual-mind", "kanuri-heart-chinese-tongue", "the-entrepreneurial-polyglot"],
  },
  {
    title: "A Kanuri Heart, A Chinese Tongue",
    slug: "kanuri-heart-chinese-tongue",
    subtitle: "Language, culture, identity, and movement across worlds",
    category: "Languages / Culture",
    description: "A personal and cross-cultural work about identity, language, movement, and the experience of carrying one cultural home while learning to speak deeply within another.",
    audience: "Multilingual readers, students of culture and identity, translators, travellers, and readers interested in cross-cultural formation.",
    learn: [
      "How language learning can reshape identity without erasing origin.",
      "How cultural immersion changes perception, communication, and belonging.",
      "How a person can live meaningfully between distinct linguistic and cultural worlds.",
    ],
    contents: ["Home and identity", "Language and immersion", "Living between worlds"],
    authorNote: "Forthcoming from Musa Allama.",
    price: "Coming soon",
    formats: ["Digital", "Print"],
    coverTone: "burgundy",
    related: ["a-multilingual-mind", "engineering-the-journey", "the-global-seeker"],
  },
];
